package constants

var DefaultCoreSettings = map[string]any{
	"timerMode":                    "stopwatch",
	"breaksEnabled":                false,
	"workDurationMinutes":          25,
	"shortBreakMinutes":            5,
	"longBreakMinutes":             15,
	"longBreakEnabled":             true,
	"cyclesBeforeLongBreak":        4,
	"autoStartBreaks":              true,
	"autoStartWork":                false,
	"boundaryNotificationsEnabled": true,
	"boundarySoundEnabled":         true,
	"alertSoundPreset":             "chime",
	"alertUrgency":                 "normal",
	"alertIconEnabled":             true,
	"inactivityAlertsEnabled":      true,
	"inactivityThresholdMinutes":   60,
	"inactivityRepeatMinutes":      60,
	"updateChecksEnabled":          true,
	"updatePromptEnabled":          true,
	"updateChannel":                string("stable"),
	"repoSort":                     string("chronological_asc"),
	"streamSort":                   string("chronological_asc"),
	"issueSort":                    string("priority"),
	"habitSort":                    string("schedule"),
	"awayModeEnabled":              false,
	"frozenStreakKinds":            []string{"focus_days", "checkin_days"},
	"restWeekdays":                 []int{},
	"restSpecificDates":            []string{},
	"dailyPlanRollbackMinutes":     5,
}
